version: '3.1'
services:
  goteam:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=goteam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_DB=goteam
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
